name: Continuous Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-install:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install UV Package
      run: |
        pip install uv
    
    - name: Install Project Dependencies
      run: |
        make install
    
    - name: Run Linter
      run: |
        make lint
